[package]
name = "rpi-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nrf24l01 = "0.2.0"
rppal = "0.14.1"
sdl2 = "0.35.2"
